### ISSUE TITLE
Winning the game

### ISSUE THREAD

**Issue by ofvoler** [0x0800/2048-CUPCAKES#1]
I love this game! It's very smooth, everything runs and looks very nice. However, when you win the game and select the option "keep going", if you get a tile higher than "2048" it shows no image. I would suggest adding a few images for tiles higher than 2048. Other than that, it looks great!

**Comment by petrosh** [comment]
Hi, I added 4096 tile: "2017 Confetti Vanilla"
have fun!
![schermata 2017-03-05 alle 15 07 01](https://cloud.githubusercontent.com/assets/4997583/23588122/ff6e9cc0-01b8-11e7-94e5-433c5bf9350b.png)
