### ISSUE TITLE
8192 tile? :)

### ISSUE THREAD

**Issue by stnever** [0x0800/2048-CUPCAKES#2]
So I'm always playing this version of the game, and sometimes I can get up to the 4096 tile, which was missing until yesterday.

As soon as I saw that you had added that missing tile, I started playing to get it. Well I got a little bit carried away and... long story short... can you add the 8192 tile? :)

![2048-cupcakes-8192](https://cloud.githubusercontent.com/assets/342285/23603090/550ff510-0232-11e7-8cdc-6fb69158962b.gif)

**Comment by petrosh** [comment]
Here you go

![getimage](https://cloud.githubusercontent.com/assets/4997583/23653771/ebc0f422-032d-11e7-851d-403afc787a0a.jpg)

**Comment by stnever** [comment]
Thanks a lot!
